source:
  folder: /data/science/imap/mag/l1b/2025/10
  calibration_folder: /data/science/imap/mag/calibration/2025/10

work-folder: .work

destination:
  folder: /data/science/imap/mag/l2
  filename: imap_mag_l2_norm-mago_20251017_v000.json
