"""Make content_date field nullable

Revision ID: 44799fd8de27
Revises: d9fc61463dd6
Create Date: 2025-09-03 16:02:14.064670

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "44799fd8de27"
down_revision = "d9fc61463dd6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files", "content_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files", "content_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
