"""Added creation, modified and deleted dates

Revision ID: f7dab3ec3e42
Revises: 17c951b7b5c3
Create Date: 2025-07-30 13:00:26.206031

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f7dab3ec3e42"
down_revision = "17c951b7b5c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "date", nullable=False, new_column_name="content_date")
    op.add_column(
        "files",
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "files", sa.Column("last_modified_date", sa.DateTime(), nullable=False)
    )
    op.add_column("files", sa.Column("deletion_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "content_date", nullable=False, new_column_name="date")
    op.drop_column("files", "deletion_date")
    op.drop_column("files", "last_modified_date")
    op.drop_column("files", "creation_date")
    # ### end Alembic commands ###
