"""Add size to files table

Revision ID: 17c951b7b5c3
Revises: 3d3bf318c5ca
Create Date: 2025-03-17 10:14:07.665215

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "17c951b7b5c3"
down_revision = "3d3bf318c5ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "download_progress", ["item_name"])
    op.add_column("files", sa.Column("size", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "size")
    op.drop_constraint(None, "download_progress", type_="unique")
    # ### end Alembic commands ###
