"""Add download progress table

Revision ID: 3d3bf318c5ca
Revises: 669111c45c37
Create Date: 2025-03-17 10:13:41.529378

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d3bf318c5ca"
down_revision = "669111c45c37"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_progress",
        sa.Column("item_name", sa.String(length=32), nullable=False),
        sa.Column("progress_timestamp", sa.DateTime(), nullable=True),
        sa.Column("last_checked_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("item_name"),
        sa.UniqueConstraint("item_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("download_progress")
    # ### end Alembic commands ###
