axis:
    CATDESC: The axis of the magnetometer sensor
    UNITS: ""
    VAR_TYPE: support_data

sensor:
    CATDESC: The magnetometer sensor
    VAR_NOTES: MAGo is the outboard sensor furthest along the boom, MAGi is the inboard sensor closest to the spacecraft
    UNITS: ""
    VAR_TYPE: support_data

range:
    CATDESC: The operating ranges of the magnetometer
    UNITS: ""
    VAR_TYPE: support_data

valid_start_datetime:
    CATDESC: The start time of the validity of this calibration file
    VALIDMIN: -9223372036854775808
    VALIDMAX: 9223372036854775807
    UNITS: ns
    VAR_TYPE: metadata

gradiometer_factor:
    CATDESC: The number to multiply by the delta between the MAGo and MAGi vectors. This value will then be subtracted from the MAGo vector.
    VALIDMIN: -1
    VALIDMAX: 1
    VAR_TYPE: data

spin_average_application_factor:
    CATDESC: The amount of the the spin average offset to subtract from the data in the spin plane.
    VALIDMIN: -1
    VALIDMAX: 1
    VAR_TYPE: data

number_of_spins:
    CATDESC: The number of spins to be averaged across to acquire the spin average values
    VALIDMIN: 1
    VALIDMAX: 65535
    UNITS: ""
    VAR_TYPE: data

quality_flag_threshold:
    CATDESC: The threshold delta between MAGo and MAGi over which to indicate through the quality flag that low quality data is present
    VALIDMIN: 0
    VALIDMAX: 65535
    UNITS: nT
    VAR_TYPE: data

offsets:
    CATDESC: Offsets to be added to each sensor at each range. The offsets are in the orthogonal reference frame (ORF)
    UNITS: nT
    VAR_TYPE: data
    DEPEND_0: sensor
    DEPEND_1: range
    DEPEND_2: axis

URFTOORFO:
    CATDESC: Frame transform from the unit reference frame (URF) to the orthogonal reference frame (ORF) for MAGo
    UNITS: ""
    DEPEND_0: range

URFTOORFI:
    CATDESC: Frame transform from the unit reference frame (URF) to the orthogonal reference frame (ORF) for MAGi
    UNITS: ""
    DEPEND_0: range


