name: Dev build CI on windows

on:
# only test on click/dispatch currently - windows tests not really working
#   push:
#     paths-ignore:
#       - "README**"
#     tags:
#       - "v*"
#   pull_request:
#     branches:
#       - "*"
#     paths-ignore:
#       - "README**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# write to checks/pull-request extra permission needed by 5monkeys/cobertura-action to post coverage stats
# write packages needed by docker image step
permissions:
  id-token: write
  contents: write
  checks: write
  packages: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  PREFERED_PYTHON_VERSION: "3.12"
  MLM_LICENSE_TOKEN: ${{secrets.MLM_LICENSE_TOKEN }}
  CALIBRATION_CODE_LOCATION: "src/matlab/calibration"
jobs:

  test_on_windows:
    strategy:
      matrix:
        python-versions: ["3.10", "3.11", "3.12"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest -s --cov-config=.coveragerc --cov=src --cov-append --cov-report=xml --cov-report term-missing --cov-report=html --junitxml=test-results.xml tests

      - name: Upload Coverage report
        uses: actions/upload-artifact@v4
        if: matrix.python-versions == env.PREFERED_PYTHON_VERSION
        with:
          name: CoverageReport_${{ matrix.os }}_python${{matrix.python-versions}}_${{ env.PACKAGE_VERSION }}
          path: htmlcov
          if-no-files-found: error

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Test Results (${{ matrix.os }}) (${{ matrix.python-versions }})
          path: "test-results.xml"
          reporter: java-junit
